// Para file:// - metadata completa (copie do HTML ao adicionar notícia)
// Para HTTP usa lista.json e extrai do HTML automaticamente
window.LISTA_NOTICIAS = [
  {arquivo:"demon-slayer-nova-temporada.html",titulo:"Kimetsu no Yaiba: nova temporada confirmada para 2025",data:"2025-02-20",imagem:"https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",preview:"A produtora ufotable confirmou oficialmente a produção de uma nova temporada de Demon Slayer (Kimetsu no Yaiba)."},
  {arquivo:"one-piece-anime-milestone.html",titulo:"One Piece atinge marca histórica de 1100 episódios",data:"2025-02-18",imagem:"https://cdn.myanimelist.net/images/anime/1244/138851l.jpg",preview:"O anime One Piece alcançou a impressionante marca de 1100 episódios, consolidando-se como uma das séries animadas mais longas da história."},
  {arquivo:"jujutsu-kaisen-filme-anunciado.html",titulo:"Jujutsu Kaisen: novo filme em produção revelado",data:"2025-02-15",imagem:"https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",preview:"A MAPPA anunciou que um novo filme de Jujutsu Kaisen está em produção."},
  {arquivo:"attack-on-titan-legado.html",titulo:"Attack on Titan: documentário sobre produção do final será lançado",data:"2025-02-12",imagem:"https://cdn.myanimelist.net/images/anime/10/47347l.jpg",preview:"Um documentário exclusivo sobre a produção do final de Attack on Titan foi anunciado pela Wit Studio."},
  {arquivo:"spy-x-family-temporada-3.html",titulo:"Spy x Family: temporada 3 confirmada para outubro de 2025",data:"2025-02-10",imagem:"https://cdn.myanimelist.net/images/anime/1441/122795l.jpg",preview:"A temporada 3 de Spy x Family foi oficialmente confirmada para outubro de 2025."},
  {arquivo:"chainsaw-man-parte-2-anime.html",titulo:"Chainsaw Man: parte 2 do anime em desenvolvimento pela MAPPA",data:"2025-02-08",imagem:"https://cdn.myanimelist.net/images/anime/1806/126216l.jpg",preview:"A MAPPA está desenvolvendo a segunda parte do anime Chainsaw Man."},
  {arquivo:"my-hero-academia-final.html",titulo:"My Hero Academia: episódio final da série chega em abril",data:"2025-02-05",imagem:"https://cdn.myanimelist.net/images/anime/10/78745l.jpg",preview:"A temporada final de My Hero Academia chegará ao fim em abril de 2025."},
  {arquivo:"solo-leveling-suasong-temporada-2.html",titulo:"Solo Leveling: segunda temporada em produção pelo estúdio A-1",data:"2025-02-03",imagem:"https://cdn.myanimelist.net/images/anime/1801/142390l.jpg",preview:"A segunda temporada de Solo Leveling está em produção, confirmou o estúdio A-1 Pictures."},
  {arquivo:"frieren-manga-continua.html",titulo:"Frieren: Beyond Journey's End vence prêmio de Anime do Ano",data:"2025-01-28",imagem:"https://cdn.myanimelist.net/images/anime/1015/138006l.jpg",preview:"Frieren: Beyond Journey's End foi eleito Anime do Ano em premiação realizada em Tóquio."},
  {arquivo:"blue-lock-movie.html",titulo:"Blue Lock: filme do anime entra em produção",data:"2025-01-25",imagem:"https://cdn.myanimelist.net/images/anime/1258/126929l.jpg",preview:"Um filme de Blue Lock foi anunciado pela Eight Bit, produtora da série."},
  {arquivo:"naruto-20-anos.html",titulo:"Naruto: 20 anos de anime com evento especial e conteúdo inédito",data:"2025-01-20",imagem:"https://cdn.myanimelist.net/images/anime/1141/142503l.jpg",preview:"Naruto completa 20 anos desde a estreia do anime em 2002, e a Pierrot prepara uma celebração especial."},
  {arquivo:"vinland-saga-temporada-3.html",titulo:"Vinland Saga: temporada 3 confirmada pela MAPPA",data:"2025-01-15",imagem:"https://cdn.myanimelist.net/images/anime/1500/103005l.jpg",preview:"A MAPPA confirmou a produção da terceira temporada de Vinland Saga."},
  {arquivo:"mob-psycho-100-legacy.html",titulo:"Mob Psycho 100: retrospectiva marca 10 anos da obra de ONE",data:"2025-01-10",imagem:"https://cdn.myanimelist.net/images/anime/8/80356l.jpg",preview:"Mob Psycho 100 completa uma década desde o início da publicação do webcomic de ONE."},
  {arquivo:"dandadan-anime-streamea.html",titulo:"Dandadan: anime do Science SARU estreia em abril na Crunchyroll",data:"2025-01-05",imagem:"https://cdn.myanimelist.net/images/anime/1584/143719l.jpg",preview:"O anime Dandadan, do mangá de Yukinobu Tatsu, estreará em abril de 2025 no catálogo da Crunchyroll."}
];
